### ISSUE TITLE
Help with a List of description from Raymarine PNG's ?

### ISSUE THREAD

**Issue by BerndCirotzki** [matztam/raymarine-evo-pilot-remote#1]
Hello matztam,
I found your Github Side and in your Code a lot of Raymarine Autopilot PNG.
I Only know the Seatalk1 Sentences with Smartpilot S1.
I build a translater from NMEA2000 to NMEA0183 and to Seatalk 1 but I don't now the SeatalkNG PNG's.

Do you have a PNG List from Raymarine EVOs?
So a could translate the Seatalk 1 Sentences To SeatalkNG and back. And it would be able to control via My Opencpn Autopilot Plugin the Evolution Autopilot. :-)

Greatings from Hamburg

**Comment by matztam** [comment]
This might be helpful:
https://github.com/SignalK/signalk-autopilot/blob/master/raymarinen2k.js

**Comment by nicklasb** [comment]
Here as well:
https://github.com/canboat/canboat/blob/master/analyzer/pgn.h

There is a *lot* of proprietary chatter going on between the course computer and the actuator that I am not sure is covered anywhere. Not sure how interesting that is, though.
